# Generated by Django 3.1 on 2022-09-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220908_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Precio anterior'),
            preserve_default=False,
        ),
    ]
