# Generated by Django 3.1 on 2022-09-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220911_2259'),
        ('carts', '0002_auto_20220911_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.Variation', verbose_name='Variación'),
        ),
    ]
