# Generated by Django 3.1 on 2022-12-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/users', verbose_name='Foto de perfil'),
        ),
    ]
