# Generated by Django 3.1 on 2022-12-30 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221229_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100, verbose_name='Direccion línea 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, verbose_name='Direccion línea 2')),
                ('profile_picture', models.ImageField(upload_to='userprofile', verbose_name='Imágen de perfil')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Estado/Región')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='País')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfil de usuarios',
            },
        ),
    ]
