# Generated by Django 3.1 on 2022-12-27 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='Número de pedido')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('address_line_1', models.CharField(max_length=50, verbose_name='Dirección línea 1')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='Dirección línea 2')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
                ('state', models.CharField(max_length=50, verbose_name='Estado/Región')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('order_note', models.CharField(blank=True, max_length=100, verbose_name='Nota de pedido')),
                ('order_total', models.FloatField(verbose_name='Total pedido')),
                ('tax', models.FloatField(verbose_name='Impuesto')),
                ('status', models.CharField(choices=[('New', 'Nuevo'), ('Accepted', 'Aceptado'), ('Completed', 'Completado'), ('Cancelled', 'Cancelado')], default='New', max_length=10, verbose_name='Estado del pedido')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='Dirección IP')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='ID de pago')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Método de pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de pago')),
                ('status', models.CharField(max_length=100, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('product_price', models.FloatField(verbose_name='Precio del producto')),
                ('ordered', models.BooleanField(default=False, verbose_name='Pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Pedido')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='Pago')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('variations', models.ManyToManyField(blank=True, to='store.Variation', verbose_name='Variaciones')),
            ],
            options={
                'verbose_name': 'Producto pedido',
                'verbose_name_plural': 'Productos pedidos',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
